# name of the workflow
name: Rust

# run workflow when the condition is met
on:
# run when code is pushed on the `main` branch
  push:
    branches: [ "main" ]
# run when a pull request to the `main` branch
  pull_request:
    branches: [ "main" ]

# env variables
env:
  CARGO_TERM_COLOR: always

# jobs
jobs:
# job name
  build:
  # os to run the job on support macOS and windows also
    runs-on: ubuntu-latest
# steps for job
    steps:
    # this will get the code and set the git
    - uses: actions/checkout@v3
    # run the build
    - name: Build
    # using cargo to build
      run: cargo build --release

    # for deployment
    - name: make dir
    # create a directory
      run: mkdir app
    # put the app in it
    - name: copy
      run: mv ./target/release/RustWebserverTest ./app/axum


    # # heroku deployment
    # - uses: akhileshns/heroku-deploy@v3.13.15
    #   with:
    #   # key from repository secrets
    #     heroku_api_key: "6fe7d83d-94d3-4bce-9632-3ca870d43bc9"
    #     # name of the Heroku app
    #     heroku_app_name: "rust-webserver-test"
    #     # email from which the app is uploaded
    #     heroku_email: "danielwildegger@gmx.de"

    #     # app directory
    #     appdir: "./app"

    #     # start command
    #     procfile: "web: ./axum"
    #     # buildpack is like environment used to run the app
    #     buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"
